version: '3.9'
name: restful-echo-api
services:
  restful-echo-api:
    build: 
      dockerfile: docker/Dockerfile
      context: .
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "1323:1323"